version: '3.8'
services:
  mysql:
    image: mysql:8.0
    container_name: matchmaking-db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: battle-city-matchmaking
      MYSQL_USER: matchmaking
      MYSQL_PASSWORD: matchmaking
    volumes:
      - mysql-data:/var/lib/mysql
    ports:
      - "3306:3306"

volumes:
  mysql-data:
